#!/bin/sh
### BEGIN INIT INFO
# Provides:          git-startup.sh
# Short-Description: Launch gitlab on startup
### END INIT INFO

if [ -f /home/pi/projects/home_dev/run.sh ]; then
    echo "dali pi: setting up gitlab"
    /home/pi/projects/home_dev/run.sh git
fi

