
FROM nginx:latest

# add nginx config files to sites-available & sites-enabled
RUN mkdir /etc/nginx/conf.d/sites-available
RUN mkdir /etc/nginx/conf.d/sites-enabled
ADD nginx/conf.d/sites-available/virtual.conf /etc/nginx/conf.d/sites-available/virtual.conf
RUN cp /etc/nginx/conf.d/sites-available/virtual.conf /etc/nginx/conf.d/sites-enabled/virtual.conf

ADD nginx/conf.d/sites-available/ssh.conf /etc/nginx/conf.d/sites-available/ssh.conf
RUN cp /etc/nginx/conf.d/sites-available/ssh.conf /etc/nginx/conf.d/sites-enabled/ssh.conf

WORKDIR /
