version: "3"

services:

  gitlab:
    image: "gitlab/gitlab-ce:latest"
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://gitlab.dali.com"
      GITLAB_SKIP_PG_UPGRADE: "true"
    expose:
      - "80"
      - "22"
