version: "3"

services:
  gitlab:
    image: "ulm0/gitlab:12.10.0"
    hostname: gitlab.dali.dev
    environment:
      GITLAB_HOME: /srv/gitlab
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'https://gitlab.dali.dev'
        gitlab_rails['gitlab_shell_ssh_port'] = 2224
        letsencrypt['enable'] = false
        nginx['redirect_http_to_https'] = true
    ports:
      - '80:80'
      - '443:443'
      - '2224:22'
    privileged: true
    volumes:
    - type: bind
      source: /media/ssd/srv/gitlab/config
      target: /srv/gitlab
    - type: bind
      source: /media/ssd/srv/gitlab/logs
      target: /var/log/gitlab
    - type: bind
      source: /media/ssd/srv/gitlab/data
      target: /var/opt/gitlab
    - type: bind
      source: ./gitlab/certs
      target: /etc/gitlab/ssl
    networks:
      - gitlab

    
networks:
  gitlab: