version: "3"

services:

  gitlab:
    image: "gitlab/gitlab-ce:latest"
    restart: always
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "http://gitlab.dali.dev"
      GITLAB_SKIP_PG_UPGRADE: "true"
    expose:
      - "80"
      - "22"
    networks:
      - app-network

  container_nginx:
    build:
      context: .
      dockerfile: docker/Dockerfile_nginx
    ports:
      - "30022:22"
      - "80:80"
      - "443:443"
    networks:
      - app-network
    volumes:
      - "./nginx/certs/:/etc/ssl/certs/"
      - "./nginx/private/:/etc/ssl/private/"
      - "./nginx/snippets/:/etc/nginx/snippets/"
      - "./nginx/conf/default.conf:/etc/nginx/nginx.conf"
    depends_on:
      - gitlab

networks:
  app-network:
    driver: bridge
