version: "3"

services:
  gitlab:
    image: "ulm0/gitlab"
    privileged: true
    volumes:
    - type: bind
      source: /media/ssd/srv/gitlab/config
      target: /etc/gitlab/config
    - type: bind
      source: /media/ssd/srv/gitlab/logs
      target: /etc/gitlab/logs
    - type: bind
      source: /media/ssd/srv/gitlab/data
      target: /etc/gitlab/data
