version: "3"

services:
  gitlab:
    image: "gitlab/gitlab-ce:latest"
    restart: always
    hostname: "gitlab.dali.com"
    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url "https://gitlab.dali.com"
      - GITLAB_SKIP_PG_UPGRADE: "true"
    ports:
      - "80:80"
      - "443:443"
      - "22:22"
